### ISSUE TITLE
分类出错！

### ISSUE THREAD

**Issue by swzaaaaaaa** [hht1996ok/VA-GCN#2]
File "train_classification.py", line 133, in main
    classifier = model.get_model(num_class, normal_channel=args.use_normals)
TypeError: __init__() got an unexpected keyword argument 'normal_channel'

请问代码，这部分是不是有问题！

**Comment by hht1996ok** [comment]
抱歉，我将修改一下我的代码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: swzaaaaaaa ***@***.***&gt;
发送时间: 2021年9月7日 10:35
收件人: hht1996ok/VA-GCN ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[hht1996ok/VA-GCN] 分类出错！ (#2)





 
File "train_classification.py", line 133, in main
 classifier = model.get_model(num_class, normal_channel=args.use_normals)
 TypeError: init() got an unexpected keyword argument 'normal_channel'
 
请问代码，这部分是不是有问题！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by swzaaaaaaa** [comment]
![image](https://user-images.githubusercontent.com/43643616/132276347-f6702baf-7af7-4a5e-aba3-a0a1acb19664.png)
，我看这一段需要PointNet++的代码，请问，我需要下载下来放到哪里吗？谢谢

**Comment by hht1996ok** [comment]
我上传版本可能没有改，可以把pointnet++_utils改成VAGCN_utils



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: swzaaaaaaa ***@***.***&gt;
发送时间: 2021年9月7日 10:46
收件人: hht1996ok/VA-GCN ***@***.***&gt;
抄送: hht1996ok ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[hht1996ok/VA-GCN] 分类出错！ (#2)





 

 ，我看这一段需要PointNet++的代码，请问，我需要下载下来放到哪里吗？谢谢
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hht1996ok** [comment]
然后可以删除get_model函数中输入的normal channel变量。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: swzaaaaaaa ***@***.***&gt;
发送时间: 2021年9月7日 10:46
收件人: hht1996ok/VA-GCN ***@***.***&gt;
抄送: hht1996ok ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[hht1996ok/VA-GCN] 分类出错！ (#2)





 

 ，我看这一段需要PointNet++的代码，请问，我需要下载下来放到哪里吗？谢谢
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by swzaaaaaaa** [comment]
好的，感谢，请问这样的话，是默认有法向量的吗？

**Comment by swzaaaaaaa** [comment]
Traceback (most recent call last):
  File "train_classification.py", line 232, in <module>
    main(args)
  File "train_classification.py", line 173, in main
    instance_acc, class_acc = test(classifier.eval(), testDataLoader, num_class=num_class)
  File "train_classification.py", line 63, in test
    pred, _ = classifier(points)
  File "/root/anaconda3/envs/pytorch1.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/data/private/swz/VA-GCN-VA-GCN/models/VAGCN_cls.py", line 247, in forward
    pos, norm, batch = data.pos, data.norm, data.batch
AttributeError: 'Tensor' object has no attribute 'pos'

还有个问题。。

**Comment by hht1996ok** [comment]
新的代码已经更新，我本地可以正常运行了。

**Comment by swzaaaaaaa** [comment]
好的，谢谢

**Comment by swzaaaaaaa** [comment]
还是出错啊
![image](https://user-images.githubusercontent.com/43643616/132290570-c9764b4b-40fb-4191-8702-0dcaf07faa51.png)

**Comment by hht1996ok** [comment]
抱歉，删除错误语句的第二个变量即可。





------------------ 原始邮件 ------------------
发件人: swzaaaaaaa ***@***.***&gt;
发送时间: 2021年9月7日 13:44
收件人: hht1996ok/VA-GCN ***@***.***&gt;
抄送: hht1996ok ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[hht1996ok/VA-GCN] 分类出错！ (#2)





 
还是出错啊
 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by swzaaaaaaa** [comment]
pred, trans_feat = classifier(points)
  loss = criterion(pred, target.long(), trans_feat)
  pred_choice = pred.data.max(1)[1]

不对把，trans_feat 后面用到了。。

**Comment by hht1996ok** [comment]
已改
